test workflow

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -15,6 +15,18 @@ on:
     branches: [ "main" ]
 
 jobs:
+  validate:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'push'
+    steps:
+      - name: Check for previous workflow run
+        run: |
+          set -e
+          status=$(curl -s https://api.github.com/repos/${{github.repository}}/actions/runs?event_id=${{github.event_id}} | jq -r '.total_count')
+          if [ $status -gt 0 ]; then
+            echo "Error: previous workflow run still in progress"
+            exit 1
+          fi
   env-setup:
     runs-on: ubuntu-latest
     outputs:
